name: Test Plan Action
# Triggered by changes in code-specific or job-specific files

on:
  pull_request:
    paths:
      - 'test-plan/**'
  push:
    branches:
      - main
    paths:
      - 'test-plan/**'
  workflow_dispatch:

jobs:
  run-crapi-test-plan:
    environment: Dev
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: ./test-plan
        with:
          plan: "continuous_testing_levo_ai_auth0:ws/continuous_testing:app/Demo_crAPI:tp/Demo_crAPI"
          base64_env: ${{ secrets.TEST_PLAN_ENV }}
          authorization-key: ${{ secrets.LEVO_REFRESH_TOKEN }}
          organization-id: ${{ secrets.LEVO_CI_ORGANIZATION_ID }}
          target: http://crapi.levo.ai
          fail-on-failed-tests: false
          saas-url: https://api.dev.levo.ai
          report: false
          cli_extra_args: "-v INFO"
