name: Test Schema Conformance Action
# Triggered by changes in code-specific or job-specific files

on:
  pull_request:
    paths:
      - 'test-plan/**'
  push:
    branches:
      - main
    paths:
      - 'test-plan/**'
  workflow_dispatch:

jobs:
  run-crapi-conformance:
    environment: Dev
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: |
          echo Token: ${{ secrets.LEVO_REFRESH_TOKEN }}
          echo Org: ${{ secrets.LEVO_CI_ORGANIZATION_ID }}
        shell: bash
      - uses: ./test-plan
        with:
          plan: continuous_testing_levo_ai:ws/continuous_testing:app/Demo_crAPI:tp/Demo_crAPI
          env: ${{ secrets.TEST_PLAN_ENV }}
          authorization-key: ${{ secrets.LEVO_REFRESH_TOKEN }}
          organization-id: ${{ secrets.LEVO_CI_ORGANIZATION_ID }}
          target: http://crapi.levo.ai
          fail-on-failed-tests: false
          saas-url: https://api.dev.levo.ai
          report-to-saas: false

  
  